name: Heroku Awake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://tgfilelnk.herokuapp.com" 
